version: '3.4'

services:
  webapi:
    container_name: "payments-gateway-api"
    image: ${DOCKER_REGISTRY-}webapi
    ports:
      - 5000:80
      - 5001:443
    build:
      context: .
      dockerfile: src/Presentation/WebApi/Dockerfile
    environment:
      - "UseInMemoryDatabase=false"
      - "RunEFCoreMigrations=true"
      - "ForwardHeadersEnabled=true"
      - "DataProtectionKeysConfig__Enabled=true"
      - "DataProtectionKeysConfig__RedisServer=webapi-redis,6379"
      - "ConnectionStrings__DefaultConnection=Server=webapi-db;database=PaymentsGatewayApiDb;User Id=sa;Password=Password_123;"
      - "OpenTelemetryConfig__Enabled=true"
      - "OpenTelemetryConfig__JaegerExporter__AgentHost=webapi-jaeger"
      - "OpenTelemetryConfig__JaegerExporter__AgentPort=6831"
      - "Serilog__WriteTo__1__Args__serverUrl=http://webapi-loki:3100"
      - "Serilog__WriteTo__2__Args__serverUrl=http://host.docker.internal:5341"
    depends_on:
      - webapi-db
      - webapi-redis
      - webapi-seq
      - webapi-jaeger
      - webapi-loki
    networks:
      - clean-architecture-network

  webapi-db:
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    container_name: webapi-database
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password_123
    ports:
      - "1433:1433"
    volumes: 
          - sqlsystem:/var/opt/mssql/
          - sqldata:/var/opt/sqlserver/data
          - sqllog:/var/opt/sqlserver/log
          - sqlbackup:/var/opt/sqlserver/backup
    networks:
      - clean-architecture-network

  webapi-redis:
    container_name: webapi-redis-server
    image: redis:6.2.6
    hostname: webapi-redis-host
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    networks:
      - clean-architecture-network

  webapi-redis-commander:
    container_name: webapi-redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:webapi-redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 8081:8081
    depends_on:
      - webapi-redis
    networks:
      - clean-architecture-network

  webapi-jaeger:
    container_name: webapi-jaeger
    image: jaegertracing/all-in-one:1.24
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    restart: unless-stopped
    ports:
      - 16686:16686 #ui
      - 6831:6831  #ingest / otmp receiver
    networks:
      - clean-architecture-network

  webapi-seq:
    container_name: "webapi-seq"  
    image: datalust/seq:2022.1
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
      #- "5341:5341"
    volumes:
      - seq-data:/data
    networks:
      - clean-architecture-network

  webapi-loki:
    container_name: "webapi-loki"
    image: grafana/loki:main-7b214e2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - clean-architecture-network

  webapi-grafana:
    container_name: "webapi-grafana"  
    image: grafana/grafana:8.4.6
    ports:
      - "3000:3000"
    networks:
      - clean-architecture-network
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    depends_on:
      - webapi-loki
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  webapi-prometheus:
    container_name: "webapi-prometheus"
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - clean-architecture-network

volumes:
  redis-data:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup:
  seq-data:

networks:
  clean-architecture-network: {}