apiVersion: 1

deleteDatasources:
  - name: Loki
    orgId: 1
  - name: Prometheus
    orgId: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    uid: BzeIY687z
    url: http://webapi-loki:3100
    password:
    user:
    database:
    basicAuth: false
    basicAuthUser:
    basicAuthPassword:
    withCredentials:
    isDefault: true
    version: 1
    editable: false
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: NHHSL6U7k
    url: http://webapi-prometheus:9090
    jsonData:
      httpMethod: POST
    password:
    user:
    database:
    basicAuth: false
    basicAuthUser:
    basicAuthPassword:
    withCredentials:
    isDefault: false
    version: 1
    editable: false